version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fastapidb
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  redis:
    image: redis:latest
  
  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  
  email_service:
    image: zus666/simple_email_sender:latest
    env_file:
      - .env_notify
    depends_on:
      - rabbitmq
    restart: always
  
  users_service:
    image: zus666/users_service:latest
    restart: always
    depends_on:
      - rabbitmq
    env_file:
      - .env_users
    ports:
      - "8000:8000"


volumes:
  postgres_data:
  rabbitmq_data: