"""init.

Revision ID: 16ff2901c210
Revises:
Create Date: 2024-02-19 21:38:34.614756

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '16ff2901c210'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('email', sa.String(length=100), nullable=False, comment='User email'),
        sa.Column(
            'is_active',
            sa.Boolean(),
            nullable=False,
            comment='User is active status',
            server_default='FALSE',
        ),
        sa.Column(
            'is_admin',
            sa.Boolean(),
            nullable=False,
            comment='User is admin status',
            server_default='FALSE',
        ),
        sa.Column(
            'password', sa.String(length=256), nullable=False, comment='User password'
        ),
        sa.Column(
            'id', sa.BigInteger(), sa.Identity(always=True, cycle=True), nullable=False
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
    )
    op.create_check_constraint(
        'email_regex',
        'users',
        "email ~ '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}$'",
    )
    op.create_table(
        'profiles',
        sa.Column('first_name', sa.String(length=100), nullable=False),
        sa.Column('last_name', sa.String(length=100), nullable=False),
        sa.Column(
            'id', sa.BigInteger(), sa.Identity(always=True, cycle=True), nullable=False
        ),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profiles')
    op.drop_table('users')
    # ### end Alembic commands ###
