"""profile nullable fields.

Revision ID: 027b81e60abf
Revises: 16ff2901c210
Create Date: 2024-03-03 21:42:27.403196

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '027b81e60abf'
down_revision: Union[str, None] = '16ff2901c210'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'profiles', 'first_name', existing_type=sa.VARCHAR(length=100), nullable=True
    )
    op.alter_column(
        'profiles', 'last_name', existing_type=sa.VARCHAR(length=100), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'profiles', 'last_name', existing_type=sa.VARCHAR(length=100), nullable=False
    )
    op.alter_column(
        'profiles', 'first_name', existing_type=sa.VARCHAR(length=100), nullable=False
    )
    # ### end Alembic commands ###
