"""add avatar to profile.

Revision ID: ae81f0c4aeab
Revises: a2cf2b7464d7
Create Date: 2024-04-20 15:20:01.293731

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'ae81f0c4aeab'
down_revision: Union[str, None] = 'a2cf2b7464d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('avatar', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'avatar')
    # ### end Alembic commands ###
